export type PhoneCodeOption = {
  value: string;
  numberCode: string;
  letterCode: string;
  label: string;
};

export const phoneCodes: PhoneCodeOption[] = [
  {
    value: '93AF',
    numberCode: '93',
    letterCode: 'AF',
    label: 'Afghanistan (+93)',
  },
  {
    value: '358AX',
    numberCode: '358',
    letterCode: 'AX',
    label: 'Åland Islands (+358)',
  },
  {
    value: '355AL',
    numberCode: '355',
    letterCode: 'AL',
    label: 'Albania (+355)',
  },
  {
    value: '213DZ',
    numberCode: '213',
    letterCode: 'DZ',
    label: 'Algeria (+213)',
  },
  {
    value: '1AS',
    numberCode: '1',
    letterCode: 'AS',
    label: 'American Samoa (+1)',
  },
  {
    value: '376AD',
    numberCode: '376',
    letterCode: 'AD',
    label: 'Andorra (+376)',
  },
  {
    value: '244AO',
    numberCode: '244',
    letterCode: 'AO',
    label: 'Angola (+244)',
  },
  {
    value: '1AI',
    numberCode: '1',
    letterCode: 'AI',
    label: 'Anguilla (+1)',
  },
  {
    value: '1AG',
    numberCode: '1',
    letterCode: 'AG',
    label: 'Antigua & Barbuda (+1)',
  },
  {
    value: '54AR',
    numberCode: '54',
    letterCode: 'AR',
    label: 'Argentina (+54)',
  },
  {
    value: '374AM',
    numberCode: '374',
    letterCode: 'AM',
    label: 'Armenia (+374)',
  },
  {
    value: '297AW',
    numberCode: '297',
    letterCode: 'AW',
    label: 'Aruba (+297)',
  },
  {
    value: '61AU',
    numberCode: '61',
    letterCode: 'AU',
    label: 'Australia (+61)',
  },
  {
    value: '43AT',
    numberCode: '43',
    letterCode: 'AT',
    label: 'Austria (+43)',
  },
  {
    value: '994AZ',
    numberCode: '994',
    letterCode: 'AZ',
    label: 'Azerbaijan (+994)',
  },
  {
    value: '1BS',
    numberCode: '1',
    letterCode: 'BS',
    label: 'Bahamas (+1)',
  },
  {
    value: '973BH',
    numberCode: '973',
    letterCode: 'BH',
    label: 'Bahrain (+973)',
  },
  {
    value: '880BD',
    numberCode: '880',
    letterCode: 'BD',
    label: 'Bangladesh (+880)',
  },
  {
    value: '1BB',
    numberCode: '1',
    letterCode: 'BB',
    label: 'Barbados (+1)',
  },
  {
    value: '375BY',
    numberCode: '375',
    letterCode: 'BY',
    label: 'Belarus (+375)',
  },
  {
    value: '32BE',
    numberCode: '32',
    letterCode: 'BE',
    label: 'Belgium (+32)',
  },
  {
    value: '501BZ',
    numberCode: '501',
    letterCode: 'BZ',
    label: 'Belize (+501)',
  },
  {
    value: '229BJ',
    numberCode: '229',
    letterCode: 'BJ',
    label: 'Benin (+229)',
  },
  {
    value: '1BM',
    numberCode: '1',
    letterCode: 'BM',
    label: 'Bermuda (+1)',
  },
  {
    value: '975BT',
    numberCode: '975',
    letterCode: 'BT',
    label: 'Bhutan (+975)',
  },
  {
    value: '591BO',
    numberCode: '591',
    letterCode: 'BO',
    label: 'Bolivia (+591)',
  },
  {
    value: '599BQ',
    numberCode: '599',
    letterCode: 'BQ',
    label: 'Bonaire, Sint Eustatius and Saba (+599)',
  },
  {
    value: '387BA',
    numberCode: '387',
    letterCode: 'BA',
    label: 'Bosnia & Herzegovina (+387)',
  },
  {
    value: '267BW',
    numberCode: '267',
    letterCode: 'BW',
    label: 'Botswana (+267)',
  },
  {
    value: '55BR',
    numberCode: '55',
    letterCode: 'BR',
    label: 'Brazil (+55)',
  },
  {
    value: '246IO',
    numberCode: '246',
    letterCode: 'IO',
    label: 'British Indian Ocean Territory (+246)',
  },
  {
    value: '1VG',
    numberCode: '1',
    letterCode: 'VG',
    label: 'British Virgin Islands (+1)',
  },
  {
    value: '673BN',
    numberCode: '673',
    letterCode: 'BN',
    label: 'Brunei (+673)',
  },
  {
    value: '359BG',
    numberCode: '359',
    letterCode: 'BG',
    label: 'Bulgaria (+359)',
  },
  {
    value: '226BF',
    numberCode: '226',
    letterCode: 'BF',
    label: 'Burkina Faso (+226)',
  },
  {
    value: '257BI',
    numberCode: '257',
    letterCode: 'BI',
    label: 'Burundi (+257)',
  },
  {
    value: '855KH',
    numberCode: '855',
    letterCode: 'KH',
    label: 'Cambodia (+855)',
  },
  {
    value: '237CM',
    numberCode: '237',
    letterCode: 'CM',
    label: 'Cameroon (+237)',
  },
  {
    value: '1CA',
    numberCode: '1',
    letterCode: 'CA',
    label: 'Canada (+1)',
  },
  {
    value: '238CV',
    numberCode: '238',
    letterCode: 'CV',
    label: 'Cape Verde (+238)',
  },
  {
    value: '1KY',
    numberCode: '1',
    letterCode: 'KY',
    label: 'Cayman Islands (+1)',
  },
  {
    value: '236CF',
    numberCode: '236',
    letterCode: 'CF',
    label: 'Central African Republic (+236)',
  },
  {
    value: '235TD',
    numberCode: '235',
    letterCode: 'TD',
    label: 'Chad (+235)',
  },
  {
    value: '56CL',
    numberCode: '56',
    letterCode: 'CL',
    label: 'Chile (+56)',
  },
  {
    value: '86CN',
    numberCode: '86',
    letterCode: 'CN',
    label: 'China (+86)',
  },
  {
    value: '61CX',
    numberCode: '61',
    letterCode: 'CX',
    label: 'Christmas Island (+61)',
  },
  {
    value: '61CC',
    numberCode: '61',
    letterCode: 'CC',
    label: 'Cocos (Keeling) Islands (+61)',
  },
  {
    value: '57CO',
    numberCode: '57',
    letterCode: 'CO',
    label: 'Colombia (+57)',
  },
  {
    value: '269KM',
    numberCode: '269',
    letterCode: 'KM',
    label: 'Comoros (+269)',
  },
  {
    value: '242CG',
    numberCode: '242',
    letterCode: 'CG',
    label: 'Congo (+242)',
  },
  {
    value: '682CK',
    numberCode: '682',
    letterCode: 'CK',
    label: 'Cook Islands (+682)',
  },
  {
    value: '506CR',
    numberCode: '506',
    letterCode: 'CR',
    label: 'Costa Rica (+506)',
  },
  {
    value: '225CI',
    numberCode: '225',
    letterCode: 'CI',
    label: 'Côte d’Ivoire (+225)',
  },
  {
    value: '385HR',
    numberCode: '385',
    letterCode: 'HR',
    label: 'Croatia (+385)',
  },
  {
    value: '53CU',
    numberCode: '53',
    letterCode: 'CU',
    label: 'Cuba (+53)',
  },
  {
    value: '599CW',
    numberCode: '599',
    letterCode: 'CW',
    label: 'Curaçao (+599)',
  },
  {
    value: '357CY',
    numberCode: '357',
    letterCode: 'CY',
    label: 'Cyprus (+357)',
  },
  {
    value: '420CZ',
    numberCode: '420',
    letterCode: 'CZ',
    label: 'Czechia (+420)',
  },
  {
    value: '243CD',
    numberCode: '243',
    letterCode: 'CD',
    label: 'Democratic Republic of the Congo (+243)',
  },
  {
    value: '45DK',
    numberCode: '45',
    letterCode: 'DK',
    label: 'Denmark (+45)',
  },
  {
    value: '253DJ',
    numberCode: '253',
    letterCode: 'DJ',
    label: 'Djibouti (+253)',
  },
  {
    value: '1DM',
    numberCode: '1',
    letterCode: 'DM',
    label: 'Dominica (+1)',
  },
  {
    value: '1DO',
    numberCode: '1',
    letterCode: 'DO',
    label: 'Dominican Republic (+1)',
  },
  {
    value: '593EC',
    numberCode: '593',
    letterCode: 'EC',
    label: 'Ecuador (+593)',
  },
  {
    value: '20EG',
    numberCode: '20',
    letterCode: 'EG',
    label: 'Egypt (+20)',
  },
  {
    value: '503SV',
    numberCode: '503',
    letterCode: 'SV',
    label: 'El Salvador (+503)',
  },
  {
    value: '240GQ',
    numberCode: '240',
    letterCode: 'GQ',
    label: 'Equatorial Guinea (+240)',
  },
  {
    value: '291ER',
    numberCode: '291',
    letterCode: 'ER',
    label: 'Eritrea (+291)',
  },
  {
    value: '372EE',
    numberCode: '372',
    letterCode: 'EE',
    label: 'Estonia (+372)',
  },
  {
    value: '268SZ',
    numberCode: '268',
    letterCode: 'SZ',
    label: 'Eswatini (+268)',
  },
  {
    value: '251ET',
    numberCode: '251',
    letterCode: 'ET',
    label: 'Ethiopia (+251)',
  },
  {
    value: '500FK',
    numberCode: '500',
    letterCode: 'FK',
    label: 'Falkland Islands (Islas Malvinas) (+500)',
  },
  {
    value: '298FO',
    numberCode: '298',
    letterCode: 'FO',
    label: 'Faroe Islands (+298)',
  },
  {
    value: '679FJ',
    numberCode: '679',
    letterCode: 'FJ',
    label: 'Fiji (+679)',
  },
  {
    value: '358FI',
    numberCode: '358',
    letterCode: 'FI',
    label: 'Finland (+358)',
  },
  {
    value: '33FR',
    numberCode: '33',
    letterCode: 'FR',
    label: 'France (+33)',
  },
  {
    value: '594GF',
    numberCode: '594',
    letterCode: 'GF',
    label: 'French Guiana (+594)',
  },
  {
    value: '689PF',
    numberCode: '689',
    letterCode: 'PF',
    label: 'French Polynesia (+689)',
  },
  {
    value: '241GA',
    numberCode: '241',
    letterCode: 'GA',
    label: 'Gabon (+241)',
  },
  {
    value: '220GM',
    numberCode: '220',
    letterCode: 'GM',
    label: 'Gambia (+220)',
  },
  {
    value: '995GE',
    numberCode: '995',
    letterCode: 'GE',
    label: 'Georgia (+995)',
  },
  {
    value: '49DE',
    numberCode: '49',
    letterCode: 'DE',
    label: 'Germany (+49)',
  },
  {
    value: '233GH',
    numberCode: '233',
    letterCode: 'GH',
    label: 'Ghana (+233)',
  },
  {
    value: '350GI',
    numberCode: '350',
    letterCode: 'GI',
    label: 'Gibraltar (+350)',
  },
  {
    value: '30GR',
    numberCode: '30',
    letterCode: 'GR',
    label: 'Greece (+30)',
  },
  {
    value: '299GL',
    numberCode: '299',
    letterCode: 'GL',
    label: 'Greenland (+299)',
  },
  {
    value: '1GD',
    numberCode: '1',
    letterCode: 'GD',
    label: 'Grenada (+1)',
  },
  {
    value: '590GP',
    numberCode: '590',
    letterCode: 'GP',
    label: 'Guadeloupe (+590)',
  },
  {
    value: '1GU',
    numberCode: '1',
    letterCode: 'GU',
    label: 'Guam (+1)',
  },
  {
    value: '502GT',
    numberCode: '502',
    letterCode: 'GT',
    label: 'Guatemala (+502)',
  },
  {
    value: '44GG',
    numberCode: '44',
    letterCode: 'GG',
    label: 'Guernsey (+44)',
  },
  {
    value: '224GN',
    numberCode: '224',
    letterCode: 'GN',
    label: 'Guinea (+224)',
  },
  {
    value: '245GW',
    numberCode: '245',
    letterCode: 'GW',
    label: 'Guinea-Bissau (+245)',
  },
  {
    value: '592GY',
    numberCode: '592',
    letterCode: 'GY',
    label: 'Guyana (+592)',
  },
  {
    value: '509HT',
    numberCode: '509',
    letterCode: 'HT',
    label: 'Haiti (+509)',
  },
  {
    value: '504HN',
    numberCode: '504',
    letterCode: 'HN',
    label: 'Honduras (+504)',
  },
  {
    value: '852HK',
    numberCode: '852',
    letterCode: 'HK',
    label: 'Hong Kong (+852)',
  },
  {
    value: '36HU',
    numberCode: '36',
    letterCode: 'HU',
    label: 'Hungary (+36)',
  },
  {
    value: '354IS',
    numberCode: '354',
    letterCode: 'IS',
    label: 'Iceland (+354)',
  },
  {
    value: '91IN',
    numberCode: '91',
    letterCode: 'IN',
    label: 'India (+91)',
  },
  {
    value: '62ID',
    numberCode: '62',
    letterCode: 'ID',
    label: 'Indonesia (+62)',
  },
  {
    value: '964IQ',
    numberCode: '964',
    letterCode: 'IQ',
    label: 'Iraq (+964)',
  },
  {
    value: '353IE',
    numberCode: '353',
    letterCode: 'IE',
    label: 'Ireland (+353)',
  },
  {
    value: '44IM',
    numberCode: '44',
    letterCode: 'IM',
    label: 'Isle of Man (+44)',
  },
  {
    value: '972IL',
    numberCode: '972',
    letterCode: 'IL',
    label: 'Israel (+972)',
  },
  {
    value: '39IT',
    numberCode: '39',
    letterCode: 'IT',
    label: 'Italy (+39)',
  },
  {
    value: '1JM',
    numberCode: '1',
    letterCode: 'JM',
    label: 'Jamaica (+1)',
  },
  {
    value: '81JP',
    numberCode: '81',
    letterCode: 'JP',
    label: 'Japan (+81)',
  },
  {
    value: '44JE',
    numberCode: '44',
    letterCode: 'JE',
    label: 'Jersey (+44)',
  },
  {
    value: '962JO',
    numberCode: '962',
    letterCode: 'JO',
    label: 'Jordan (+962)',
  },
  {
    value: '7KZ',
    numberCode: '7',
    letterCode: 'KZ',
    label: 'Kazakhstan (+7)',
  },
  {
    value: '254KE',
    numberCode: '254',
    letterCode: 'KE',
    label: 'Kenya (+254)',
  },
  {
    value: '686KI',
    numberCode: '686',
    letterCode: 'KI',
    label: 'Kiribati (+686)',
  },
  {
    value: '383XK',
    numberCode: '383',
    letterCode: 'XK',
    label: 'Kosovo (+383)',
  },
  {
    value: '965KW',
    numberCode: '965',
    letterCode: 'KW',
    label: 'Kuwait (+965)',
  },
  {
    value: '996KG',
    numberCode: '996',
    letterCode: 'KG',
    label: 'Kyrgyzstan (+996)',
  },
  {
    value: '856LA',
    numberCode: '856',
    letterCode: 'LA',
    label: 'Laos (+856)',
  },
  {
    value: '371LV',
    numberCode: '371',
    letterCode: 'LV',
    label: 'Latvia (+371)',
  },
  {
    value: '961LB',
    numberCode: '961',
    letterCode: 'LB',
    label: 'Lebanon (+961)',
  },
  {
    value: '266LS',
    numberCode: '266',
    letterCode: 'LS',
    label: 'Lesotho (+266)',
  },
  {
    value: '231LR',
    numberCode: '231',
    letterCode: 'LR',
    label: 'Liberia (+231)',
  },
  {
    value: '218LY',
    numberCode: '218',
    letterCode: 'LY',
    label: 'Libya (+218)',
  },
  {
    value: '423LI',
    numberCode: '423',
    letterCode: 'LI',
    label: 'Liechtenstein (+423)',
  },
  {
    value: '370LT',
    numberCode: '370',
    letterCode: 'LT',
    label: 'Lithuania (+370)',
  },
  {
    value: '352LU',
    numberCode: '352',
    letterCode: 'LU',
    label: 'Luxembourg (+352)',
  },
  {
    value: '853MO',
    numberCode: '853',
    letterCode: 'MO',
    label: 'Macau (+853)',
  },
  {
    value: '389MK',
    numberCode: '389',
    letterCode: 'MK',
    label: 'Macedonia (+389)',
  },
  {
    value: '261MG',
    numberCode: '261',
    letterCode: 'MG',
    label: 'Madagascar (+261)',
  },
  {
    value: '265MW',
    numberCode: '265',
    letterCode: 'MW',
    label: 'Malawi (+265)',
  },
  {
    value: '60MY',
    numberCode: '60',
    letterCode: 'MY',
    label: 'Malaysia (+60)',
  },
  {
    value: '960MV',
    numberCode: '960',
    letterCode: 'MV',
    label: 'Maldives (+960)',
  },
  {
    value: '223ML',
    numberCode: '223',
    letterCode: 'ML',
    label: 'Mali (+223)',
  },
  {
    value: '356MT',
    numberCode: '356',
    letterCode: 'MT',
    label: 'Malta (+356)',
  },
  {
    value: '692MH',
    numberCode: '692',
    letterCode: 'MH',
    label: 'Marshall Islands (+692)',
  },
  {
    value: '596MQ',
    numberCode: '596',
    letterCode: 'MQ',
    label: 'Martinique (+596)',
  },
  {
    value: '222MR',
    numberCode: '222',
    letterCode: 'MR',
    label: 'Mauritania (+222)',
  },
  {
    value: '230MU',
    numberCode: '230',
    letterCode: 'MU',
    label: 'Mauritius (+230)',
  },
  {
    value: '262YT',
    numberCode: '262',
    letterCode: 'YT',
    label: 'Mayotte (+262)',
  },
  {
    value: '52MX',
    numberCode: '52',
    letterCode: 'MX',
    label: 'Mexico (+52)',
  },
  {
    value: '691FM',
    numberCode: '691',
    letterCode: 'FM',
    label: 'Micronesia (+691)',
  },
  {
    value: '373MD',
    numberCode: '373',
    letterCode: 'MD',
    label: 'Moldova (+373)',
  },
  {
    value: '377MC',
    numberCode: '377',
    letterCode: 'MC',
    label: 'Monaco (+377)',
  },
  {
    value: '976MN',
    numberCode: '976',
    letterCode: 'MN',
    label: 'Mongolia (+976)',
  },
  {
    value: '382ME',
    numberCode: '382',
    letterCode: 'ME',
    label: 'Montenegro (+382)',
  },
  {
    value: '1MS',
    numberCode: '1',
    letterCode: 'MS',
    label: 'Montserrat (+1)',
  },
  {
    value: '212MA',
    numberCode: '212',
    letterCode: 'MA',
    label: 'Morocco (+212)',
  },
  {
    value: '258MZ',
    numberCode: '258',
    letterCode: 'MZ',
    label: 'Mozambique (+258)',
  },
  {
    value: '95MM',
    numberCode: '95',
    letterCode: 'MM',
    label: 'Myanmar (+95)',
  },
  {
    value: '264NA',
    numberCode: '264',
    letterCode: 'NA',
    label: 'Namibia (+264)',
  },
  {
    value: '674NR',
    numberCode: '674',
    letterCode: 'NR',
    label: 'Nauru (+674)',
  },
  {
    value: '977NP',
    numberCode: '977',
    letterCode: 'NP',
    label: 'Nepal (+977)',
  },
  {
    value: '31NL',
    numberCode: '31',
    letterCode: 'NL',
    label: 'Netherlands (+31)',
  },
  {
    value: '687NC',
    numberCode: '687',
    letterCode: 'NC',
    label: 'New Caledonia (+687)',
  },
  {
    value: '64NZ',
    numberCode: '64',
    letterCode: 'NZ',
    label: 'New Zealand (+64)',
  },
  {
    value: '505NI',
    numberCode: '505',
    letterCode: 'NI',
    label: 'Nicaragua (+505)',
  },
  {
    value: '227NE',
    numberCode: '227',
    letterCode: 'NE',
    label: 'Niger (+227)',
  },
  {
    value: '234NG',
    numberCode: '234',
    letterCode: 'NG',
    label: 'Nigeria (+234)',
  },
  {
    value: '683NU',
    numberCode: '683',
    letterCode: 'NU',
    label: 'Niue (+683)',
  },
  {
    value: '672NF',
    numberCode: '672',
    letterCode: 'NF',
    label: 'Norfolk Island (+672)',
  },
  {
    value: '1MP',
    numberCode: '1',
    letterCode: 'MP',
    label: 'Northern Mariana Islands (+1)',
  },
  {
    value: '47NO',
    numberCode: '47',
    letterCode: 'NO',
    label: 'Norway (+47)',
  },
  {
    value: '968OM',
    numberCode: '968',
    letterCode: 'OM',
    label: 'Oman (+968)',
  },
  {
    value: '92PK',
    numberCode: '92',
    letterCode: 'PK',
    label: 'Pakistan (+92)',
  },
  {
    value: '680PW',
    numberCode: '680',
    letterCode: 'PW',
    label: 'Palau (+680)',
  },
  {
    value: '970PS',
    numberCode: '970',
    letterCode: 'PS',
    label: 'Palestinian Territories (+970)',
  },
  {
    value: '507PA',
    numberCode: '507',
    letterCode: 'PA',
    label: 'Panama (+507)',
  },
  {
    value: '675PG',
    numberCode: '675',
    letterCode: 'PG',
    label: 'Papua New Guinea (+675)',
  },
  {
    value: '595PY',
    numberCode: '595',
    letterCode: 'PY',
    label: 'Paraguay (+595)',
  },
  {
    value: '51PE',
    numberCode: '51',
    letterCode: 'PE',
    label: 'Peru (+51)',
  },
  {
    value: '63PH',
    numberCode: '63',
    letterCode: 'PH',
    label: 'Philippines (+63)',
  },
  {
    value: '64PN',
    numberCode: '64',
    letterCode: 'PN',
    label: 'Pitcairn Islands (+64)',
  },
  {
    value: '48PL',
    numberCode: '48',
    letterCode: 'PL',
    label: 'Poland (+48)',
  },
  {
    value: '351PT',
    numberCode: '351',
    letterCode: 'PT',
    label: 'Portugal (+351)',
  },
  {
    value: '1PR',
    numberCode: '1',
    letterCode: 'PR',
    label: 'Puerto Rico (+1)',
  },
  {
    value: '974QA',
    numberCode: '974',
    letterCode: 'QA',
    label: 'Qatar (+974)',
  },
  {
    value: '262RE',
    numberCode: '262',
    letterCode: 'RE',
    label: 'Réunion (+262)',
  },
  {
    value: '40RO',
    numberCode: '40',
    letterCode: 'RO',
    label: 'Romania (+40)',
  },
  {
    value: '7RU',
    numberCode: '7',
    letterCode: 'RU',
    label: 'Russia (+7)',
  },
  {
    value: '250RW',
    numberCode: '250',
    letterCode: 'RW',
    label: 'Rwanda (+250)',
  },
  {
    value: '685WS',
    numberCode: '685',
    letterCode: 'WS',
    label: 'Samoa (+685)',
  },
  {
    value: '378SM',
    numberCode: '378',
    letterCode: 'SM',
    label: 'San Marino (+378)',
  },
  {
    value: '239ST',
    numberCode: '239',
    letterCode: 'ST',
    label: 'São Tomé & Príncipe (+239)',
  },
  {
    value: '966SA',
    numberCode: '966',
    letterCode: 'SA',
    label: 'Saudi Arabia (+966)',
  },
  {
    value: '221SN',
    numberCode: '221',
    letterCode: 'SN',
    label: 'Senegal (+221)',
  },
  {
    value: '381RS',
    numberCode: '381',
    letterCode: 'RS',
    label: 'Serbia (+381)',
  },
  {
    value: '248SC',
    numberCode: '248',
    letterCode: 'SC',
    label: 'Seychelles (+248)',
  },
  {
    value: '232SL',
    numberCode: '232',
    letterCode: 'SL',
    label: 'Sierra Leone (+232)',
  },
  {
    value: '65SG',
    numberCode: '65',
    letterCode: 'SG',
    label: 'Singapore (+65)',
  },
  {
    value: '1SX',
    numberCode: '1',
    letterCode: 'SX',
    label: 'Sint Maarten (+1)',
  },
  {
    value: '421SK',
    numberCode: '421',
    letterCode: 'SK',
    label: 'Slovakia (+421)',
  },
  {
    value: '386SI',
    numberCode: '386',
    letterCode: 'SI',
    label: 'Slovenia (+386)',
  },
  {
    value: '677SB',
    numberCode: '677',
    letterCode: 'SB',
    label: 'Solomon Islands (+677)',
  },
  {
    value: '252SO',
    numberCode: '252',
    letterCode: 'SO',
    label: 'Somalia (+252)',
  },
  {
    value: '27ZA',
    numberCode: '27',
    letterCode: 'ZA',
    label: 'South Africa (+27)',
  },
  {
    value: '500GS',
    numberCode: '500',
    letterCode: 'GS',
    label: 'South Georgia & South Sandwich Islands (+500)',
  },
  {
    value: '82KR',
    numberCode: '82',
    letterCode: 'KR',
    label: 'South Korea (+82)',
  },
  {
    value: '211SS',
    numberCode: '211',
    letterCode: 'SS',
    label: 'South Sudan (+211)',
  },
  {
    value: '34ES',
    numberCode: '34',
    letterCode: 'ES',
    label: 'Spain (+34)',
  },
  {
    value: '94LK',
    numberCode: '94',
    letterCode: 'LK',
    label: 'Sri Lanka (+94)',
  },
  {
    value: '590BL',
    numberCode: '590',
    letterCode: 'BL',
    label: 'St Barthélemy (+590)',
  },
  {
    value: '290SH',
    numberCode: '290',
    letterCode: 'SH',
    label: 'St Helena (+290)',
  },
  {
    value: '1KN',
    numberCode: '1',
    letterCode: 'KN',
    label: 'St Kitts & Nevis (+1)',
  },
  {
    value: '1LC',
    numberCode: '1',
    letterCode: 'LC',
    label: 'St Lucia (+1)',
  },
  {
    value: '590MF',
    numberCode: '590',
    letterCode: 'MF',
    label: 'St Martin (+590)',
  },
  {
    value: '508PM',
    numberCode: '508',
    letterCode: 'PM',
    label: 'St Pierre & Miquelon (+508)',
  },
  {
    value: '1VC',
    numberCode: '1',
    letterCode: 'VC',
    label: 'St Vincent & Grenadines (+1)',
  },
  {
    value: '249SD',
    numberCode: '249',
    letterCode: 'SD',
    label: 'Sudan (+249)',
  },
  {
    value: '597SR',
    numberCode: '597',
    letterCode: 'SR',
    label: 'Suriname (+597)',
  },
  {
    value: '47SJ',
    numberCode: '47',
    letterCode: 'SJ',
    label: 'Svalbard & Jan Mayen (+47)',
  },
  {
    value: '46SE',
    numberCode: '46',
    letterCode: 'SE',
    label: 'Sweden (+46)',
  },
  {
    value: '41CH',
    numberCode: '41',
    letterCode: 'CH',
    label: 'Switzerland (+41)',
  },
  {
    value: '886TW',
    numberCode: '886',
    letterCode: 'TW',
    label: 'Taiwan (+886)',
  },
  {
    value: '992TJ',
    numberCode: '992',
    letterCode: 'TJ',
    label: 'Tajikistan (+992)',
  },
  {
    value: '255TZ',
    numberCode: '255',
    letterCode: 'TZ',
    label: 'Tanzania (+255)',
  },
  {
    value: '66TH',
    numberCode: '66',
    letterCode: 'TH',
    label: 'Thailand (+66)',
  },
  {
    value: '670TL',
    numberCode: '670',
    letterCode: 'TL',
    label: 'Timor-Leste (+670)',
  },
  {
    value: '228TG',
    numberCode: '228',
    letterCode: 'TG',
    label: 'Togo (+228)',
  },
  {
    value: '690TK',
    numberCode: '690',
    letterCode: 'TK',
    label: 'Tokelau (+690)',
  },
  {
    value: '676TO',
    numberCode: '676',
    letterCode: 'TO',
    label: 'Tonga (+676)',
  },
  {
    value: '1TT',
    numberCode: '1',
    letterCode: 'TT',
    label: 'Trinidad & Tobago (+1)',
  },
  {
    value: '216TN',
    numberCode: '216',
    letterCode: 'TN',
    label: 'Tunisia (+216)',
  },
  {
    value: '90TR',
    numberCode: '90',
    letterCode: 'TR',
    label: 'Turkey (+90)',
  },
  {
    value: '993TM',
    numberCode: '993',
    letterCode: 'TM',
    label: 'Turkmenistan (+993)',
  },
  {
    value: '1TC',
    numberCode: '1',
    letterCode: 'TC',
    label: 'Turks & Caicos Islands (+1)',
  },
  {
    value: '688TV',
    numberCode: '688',
    letterCode: 'TV',
    label: 'Tuvalu (+688)',
  },
  {
    value: '256UG',
    numberCode: '256',
    letterCode: 'UG',
    label: 'Uganda (+256)',
  },
  {
    value: '380UA',
    numberCode: '380',
    letterCode: 'UA',
    label: 'Ukraine (+380)',
  },
  {
    value: '971AE',
    numberCode: '971',
    letterCode: 'AE',
    label: 'United Arab Emirates (+971)',
  },
  {
    value: '44GB',
    numberCode: '44',
    letterCode: 'GB',
    label: 'United Kingdom (+44)',
  },
  {
    value: '1US',
    numberCode: '1',
    letterCode: 'US',
    label: 'United States (+1)',
  },
  {
    value: '598UY',
    numberCode: '598',
    letterCode: 'UY',
    label: 'Uruguay (+598)',
  },
  {
    value: '1VI',
    numberCode: '1',
    letterCode: 'VI',
    label: 'US Virgin Islands (+1)',
  },
  {
    value: '998UZ',
    numberCode: '998',
    letterCode: 'UZ',
    label: 'Uzbekistan (+998)',
  },
  {
    value: '678VU',
    numberCode: '678',
    letterCode: 'VU',
    label: 'Vanuatu (+678)',
  },
  {
    value: '379VA',
    numberCode: '379',
    letterCode: 'VA',
    label: 'Vatican City (+379)',
  },
  {
    value: '58VE',
    numberCode: '58',
    letterCode: 'VE',
    label: 'Venezuela (+58)',
  },
  {
    value: '84VN',
    numberCode: '84',
    letterCode: 'VN',
    label: 'Vietnam (+84)',
  },
  {
    value: '681WF',
    numberCode: '681',
    letterCode: 'WF',
    label: 'Wallis & Futuna (+681)',
  },
  {
    value: '212EH',
    numberCode: '212',
    letterCode: 'EH',
    label: 'Western Sahara (+212)',
  },
  {
    value: '967YE',
    numberCode: '967',
    letterCode: 'YE',
    label: 'Yemen (+967)',
  },
  {
    value: '260ZM',
    numberCode: '260',
    letterCode: 'ZM',
    label: 'Zambia (+260)',
  },
  {
    value: '263ZW',
    numberCode: '263',
    letterCode: 'ZW',
    label: 'Zimbabwe (+263)',
  },
];
