/* eslint-disable @typescript-eslint/ban-types */
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';

export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  ISO8601DateTime: string;
  JSON: Object;
  Upload: File;
};

/** Autogenerated return type of AddRestaurantAttachment. */
export type AddRestaurantAttachmentPayload = {
  __typename?: 'AddRestaurantAttachmentPayload';
  errors: Maybe<Scalars['JSON']>;
  restaurant: Restaurant;
  status: Maybe<Status>;
};

export type Attachment = {
  __typename?: 'Attachment';
  contentType: Maybe<Scalars['String']>;
  createdAt: Scalars['ISO8601DateTime'];
  id: Scalars['ID'];
  url: Scalars['String'];
};

/** Autogenerated return type of ChangeCurrentUserPassword. */
export type ChangeCurrentUserPasswordPayload = {
  __typename?: 'ChangeCurrentUserPasswordPayload';
  errors: Maybe<Scalars['JSON']>;
  status: Maybe<Status>;
};

/** Autogenerated return type of CreateEmail. */
export type CreateEmailPayload = {
  __typename?: 'CreateEmailPayload';
  email: Maybe<Email>;
  errors: Maybe<Scalars['JSON']>;
  status: Maybe<Status>;
};

/** Autogenerated return type of CreatePhone. */
export type CreatePhonePayload = {
  __typename?: 'CreatePhonePayload';
  errors: Maybe<Scalars['JSON']>;
  phone: Maybe<Phone>;
  status: Maybe<Status>;
};

/** Autogenerated return type of CreateRestaurant. */
export type CreateRestaurantPayload = {
  __typename?: 'CreateRestaurantPayload';
  errors: Maybe<Scalars['JSON']>;
  network: Maybe<Network>;
  restaurant: Maybe<Restaurant>;
  status: Maybe<Status>;
};

export type Email = {
  __typename?: 'Email';
  email: Scalars['String'];
  id: Scalars['ID'];
  isPrimary: Scalars['Boolean'];
  verificationStatus: VerificationStatusEnum;
};

export type Errors = {
  __typename?: 'Errors';
  oneTimePassword: Maybe<Array<Scalars['String']>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addRestaurantAttachment: Maybe<AddRestaurantAttachmentPayload>;
  changeCurrentUserPassword: Maybe<ChangeCurrentUserPasswordPayload>;
  createEmail: Maybe<CreateEmailPayload>;
  createPhone: Maybe<CreatePhonePayload>;
  createRestaurant: Maybe<CreateRestaurantPayload>;
  removeRestaurantAttachment: Maybe<RemoveRestaurantAttachmentPayload>;
  sendOneTimePassword: Maybe<SendOneTimePasswordPayload>;
  signinUser: Maybe<SigninUserPayload>;
  signupUser: Maybe<SignupUserPayload>;
  updateCurrentUserInfo: Maybe<UpdateCurrentUserInfoMutationPayload>;
  verifyOneTimePassword: Maybe<VerifyOneTimePasswordPayload>;
};

export type MutationAddRestaurantAttachmentArgs = {
  attachment: Scalars['Upload'];
  attachmentType?: InputMaybe<RestaurantAttachmentTypeEnum>;
  restaurantId: Scalars['ID'];
};

export type MutationChangeCurrentUserPasswordArgs = {
  newPassword: Scalars['String'];
  newPasswordConfirmation: Scalars['String'];
  oldPassword: Scalars['String'];
};

export type MutationCreateEmailArgs = {
  email: Scalars['String'];
};

export type MutationCreatePhoneArgs = {
  number: Scalars['String'];
};

export type MutationCreateRestaurantArgs = {
  name: Scalars['String'];
};

export type MutationRemoveRestaurantAttachmentArgs = {
  attachmentId: Scalars['ID'];
  attachmentType?: InputMaybe<RestaurantAttachmentTypeEnum>;
  restaurantId: Scalars['ID'];
};

export type MutationSendOneTimePasswordArgs = {
  code: Scalars['String'];
  number: Scalars['String'];
};

export type MutationSigninUserArgs = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type MutationSignupUserArgs = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type MutationUpdateCurrentUserInfoArgs = {
  firstName: Scalars['String'];
  lastName?: InputMaybe<Scalars['String']>;
};

export type MutationVerifyOneTimePasswordArgs = {
  code: Scalars['String'];
  number: Scalars['String'];
  oneTimePassword: Scalars['String'];
};

export type Network = {
  __typename?: 'Network';
  id: Scalars['ID'];
  name: Scalars['String'];
};

export type Phone = {
  __typename?: 'Phone';
  code: Scalars['String'];
  id: Scalars['ID'];
  isPrimary: Scalars['Boolean'];
  number: Scalars['String'];
  verificationStatus: VerificationStatusEnum;
};

export type Query = {
  __typename?: 'Query';
  user: Maybe<User>;
};

export type QueryUserArgs = {
  userId: Scalars['ID'];
};

/** Autogenerated return type of RemoveRestaurantAttachment. */
export type RemoveRestaurantAttachmentPayload = {
  __typename?: 'RemoveRestaurantAttachmentPayload';
  errors: Maybe<Scalars['JSON']>;
  restaurant: Restaurant;
  status: Maybe<Status>;
};

export type Restaurant = {
  __typename?: 'Restaurant';
  currencyCode: Scalars['String'];
  id: Scalars['ID'];
  images: Array<Attachment>;
  name: Scalars['String'];
};

export enum RestaurantAttachmentTypeEnum {
  Image = 'image',
}

/** Autogenerated return type of SendOneTimePassword. */
export type SendOneTimePasswordPayload = {
  __typename?: 'SendOneTimePasswordPayload';
  errors: Maybe<Scalars['JSON']>;
  status: Maybe<Status>;
};

/** Autogenerated return type of SigninUser. */
export type SigninUserPayload = {
  __typename?: 'SigninUserPayload';
  errors: Maybe<Scalars['JSON']>;
  status: Maybe<Status>;
  token: Maybe<Scalars['String']>;
  user: Maybe<User>;
};

/** Autogenerated return type of SignupUser. */
export type SignupUserPayload = {
  __typename?: 'SignupUserPayload';
  errors: Maybe<Scalars['JSON']>;
  status: Maybe<Status>;
  token: Maybe<Scalars['String']>;
  user: Maybe<User>;
};

export enum Status {
  Failure = 'failure',
  Success = 'success',
}

/** Autogenerated return type of UpdateCurrentUserInfoMutation. */
export type UpdateCurrentUserInfoMutationPayload = {
  __typename?: 'UpdateCurrentUserInfoMutationPayload';
  errors: Maybe<Scalars['JSON']>;
  status: Maybe<Status>;
  user: User;
};

export type User = {
  __typename?: 'User';
  emails: Array<Email>;
  firstName: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  kind: UserKind;
  languageCode: Scalars['String'];
  lastName: Maybe<Scalars['String']>;
  network: Maybe<Network>;
  phones: Array<Phone>;
  restaurants: Array<Restaurant>;
};

export enum UserKind {
  Anonymous = 'anonymous',
  Real = 'real',
}

export enum VerificationStatusEnum {
  Failed = 'failed',
  InProgress = 'in_progress',
  Succeeded = 'succeeded',
}

/** Autogenerated return type of VerifyOneTimePassword. */
export type VerifyOneTimePasswordPayload = {
  __typename?: 'VerifyOneTimePasswordPayload';
  errors: Errors;
  status: Maybe<Status>;
  token: Scalars['String'];
  user: User;
};

export type SendOneTimePasswordMutationVariables = Exact<{
  code: Scalars['String'];
  number: Scalars['String'];
}>;

export type SendOneTimePasswordMutation = {
  __typename?: 'Mutation';
  sendOneTimePassword: {
    __typename?: 'SendOneTimePasswordPayload';
    status: Status | null;
    errors: Object | null;
  } | null;
};

export type VerifyOneTimePasswordMutationVariables = Exact<{
  oneTimePassword: Scalars['String'];
  code: Scalars['String'];
  number: Scalars['String'];
}>;

export type VerifyOneTimePasswordMutation = {
  __typename?: 'Mutation';
  verifyOneTimePassword: {
    __typename?: 'VerifyOneTimePasswordPayload';
    status: Status | null;
    token: string;
    user: {
      __typename?: 'User';
      id: string;
      firstName: string | null;
      lastName: string | null;
      languageCode: string;
      kind: UserKind;
      phones: Array<{
        __typename?: 'Phone';
        id: string;
        code: string;
        number: string;
        isPrimary: boolean;
        verificationStatus: VerificationStatusEnum;
      }>;
      emails: Array<{
        __typename?: 'Email';
        id: string;
        email: string;
        isPrimary: boolean;
        verificationStatus: VerificationStatusEnum;
      }>;
      network: { __typename?: 'Network'; id: string; name: string } | null;
      restaurants: Array<{
        __typename?: 'Restaurant';
        id: string;
        name: string;
        currencyCode: string;
        images: Array<{
          __typename?: 'Attachment';
          id: string;
          contentType: string | null;
          url: string;
          createdAt: string;
        }>;
      }>;
    };
    errors: { __typename?: 'Errors'; oneTimePassword: Array<string> | null };
  } | null;
};

export type AttachmentFieldsFragment = {
  __typename?: 'Attachment';
  id: string;
  contentType: string | null;
  url: string;
  createdAt: string;
};

export type EmailFieldsFragment = {
  __typename?: 'Email';
  id: string;
  email: string;
  isPrimary: boolean;
  verificationStatus: VerificationStatusEnum;
};

export type NetworkFieldsFragment = { __typename?: 'Network'; id: string; name: string };

export type PhoneFieldsFragment = {
  __typename?: 'Phone';
  id: string;
  code: string;
  number: string;
  isPrimary: boolean;
  verificationStatus: VerificationStatusEnum;
};

export type RestaurantFieldsFragment = {
  __typename?: 'Restaurant';
  id: string;
  name: string;
  currencyCode: string;
  images: Array<{ __typename?: 'Attachment'; id: string; contentType: string | null; url: string; createdAt: string }>;
};

export type UserFieldsFragment = {
  __typename?: 'User';
  id: string;
  firstName: string | null;
  lastName: string | null;
  languageCode: string;
  kind: UserKind;
  phones: Array<{
    __typename?: 'Phone';
    id: string;
    code: string;
    number: string;
    isPrimary: boolean;
    verificationStatus: VerificationStatusEnum;
  }>;
  emails: Array<{
    __typename?: 'Email';
    id: string;
    email: string;
    isPrimary: boolean;
    verificationStatus: VerificationStatusEnum;
  }>;
  network: { __typename?: 'Network'; id: string; name: string } | null;
  restaurants: Array<{
    __typename?: 'Restaurant';
    id: string;
    name: string;
    currencyCode: string;
    images: Array<{
      __typename?: 'Attachment';
      id: string;
      contentType: string | null;
      url: string;
      createdAt: string;
    }>;
  }>;
};

export type AddRestaurantAttachmentMutationVariables = Exact<{
  restaurantId: Scalars['ID'];
  attachment: Scalars['Upload'];
}>;

export type AddRestaurantAttachmentMutation = {
  __typename?: 'Mutation';
  addRestaurantAttachment: {
    __typename?: 'AddRestaurantAttachmentPayload';
    status: Status | null;
    errors: Object | null;
    restaurant: {
      __typename?: 'Restaurant';
      id: string;
      name: string;
      currencyCode: string;
      images: Array<{
        __typename?: 'Attachment';
        id: string;
        contentType: string | null;
        url: string;
        createdAt: string;
      }>;
    };
  } | null;
};

export type CreateRestaurantMutationVariables = Exact<{
  name: Scalars['String'];
}>;

export type CreateRestaurantMutation = {
  __typename?: 'Mutation';
  createRestaurant: {
    __typename?: 'CreateRestaurantPayload';
    status: Status | null;
    errors: Object | null;
    restaurant: {
      __typename?: 'Restaurant';
      id: string;
      name: string;
      currencyCode: string;
      images: Array<{
        __typename?: 'Attachment';
        id: string;
        contentType: string | null;
        url: string;
        createdAt: string;
      }>;
    } | null;
    network: { __typename?: 'Network'; id: string; name: string } | null;
  } | null;
};

export type RemoveRestaurantAttachmentMutationVariables = Exact<{
  restaurantId: Scalars['ID'];
  attachmentId: Scalars['ID'];
}>;

export type RemoveRestaurantAttachmentMutation = {
  __typename?: 'Mutation';
  removeRestaurantAttachment: {
    __typename?: 'RemoveRestaurantAttachmentPayload';
    status: Status | null;
    errors: Object | null;
    restaurant: {
      __typename?: 'Restaurant';
      id: string;
      name: string;
      currencyCode: string;
      images: Array<{
        __typename?: 'Attachment';
        id: string;
        contentType: string | null;
        url: string;
        createdAt: string;
      }>;
    };
  } | null;
};

export type UpdateCurrentUserInfoMutationVariables = Exact<{
  firstName: Scalars['String'];
  lastName?: InputMaybe<Scalars['String']>;
}>;

export type UpdateCurrentUserInfoMutation = {
  __typename?: 'Mutation';
  updateCurrentUserInfo: {
    __typename?: 'UpdateCurrentUserInfoMutationPayload';
    status: Status | null;
    errors: Object | null;
    user: {
      __typename?: 'User';
      id: string;
      firstName: string | null;
      lastName: string | null;
      languageCode: string;
      kind: UserKind;
      phones: Array<{
        __typename?: 'Phone';
        id: string;
        code: string;
        number: string;
        isPrimary: boolean;
        verificationStatus: VerificationStatusEnum;
      }>;
      emails: Array<{
        __typename?: 'Email';
        id: string;
        email: string;
        isPrimary: boolean;
        verificationStatus: VerificationStatusEnum;
      }>;
      network: { __typename?: 'Network'; id: string; name: string } | null;
      restaurants: Array<{
        __typename?: 'Restaurant';
        id: string;
        name: string;
        currencyCode: string;
        images: Array<{
          __typename?: 'Attachment';
          id: string;
          contentType: string | null;
          url: string;
          createdAt: string;
        }>;
      }>;
    };
  } | null;
};

export type GetUserQueryVariables = Exact<{
  userId: Scalars['ID'];
}>;

export type GetUserQuery = {
  __typename?: 'Query';
  user: {
    __typename?: 'User';
    id: string;
    firstName: string | null;
    lastName: string | null;
    languageCode: string;
    kind: UserKind;
    phones: Array<{
      __typename?: 'Phone';
      id: string;
      code: string;
      number: string;
      isPrimary: boolean;
      verificationStatus: VerificationStatusEnum;
    }>;
    emails: Array<{
      __typename?: 'Email';
      id: string;
      email: string;
      isPrimary: boolean;
      verificationStatus: VerificationStatusEnum;
    }>;
    network: { __typename?: 'Network'; id: string; name: string } | null;
    restaurants: Array<{
      __typename?: 'Restaurant';
      id: string;
      name: string;
      currencyCode: string;
      images: Array<{
        __typename?: 'Attachment';
        id: string;
        contentType: string | null;
        url: string;
        createdAt: string;
      }>;
    }>;
  } | null;
};

export const PhoneFieldsFragmentDoc = gql`
  fragment PhoneFields on Phone {
    id
    code
    number
    isPrimary
    verificationStatus
  }
`;
export const EmailFieldsFragmentDoc = gql`
  fragment EmailFields on Email {
    id
    email
    isPrimary
    verificationStatus
  }
`;
export const NetworkFieldsFragmentDoc = gql`
  fragment NetworkFields on Network {
    id
    name
  }
`;
export const AttachmentFieldsFragmentDoc = gql`
  fragment AttachmentFields on Attachment {
    id
    contentType
    url
    createdAt
  }
`;
export const RestaurantFieldsFragmentDoc = gql`
  fragment RestaurantFields on Restaurant {
    id
    name
    currencyCode
    images {
      ...AttachmentFields
    }
  }
  ${AttachmentFieldsFragmentDoc}
`;
export const UserFieldsFragmentDoc = gql`
  fragment UserFields on User {
    id
    firstName
    lastName
    languageCode
    kind
    phones {
      ...PhoneFields
    }
    emails {
      ...EmailFields
    }
    network {
      ...NetworkFields
    }
    restaurants {
      ...RestaurantFields
    }
  }
  ${PhoneFieldsFragmentDoc}
  ${EmailFieldsFragmentDoc}
  ${NetworkFieldsFragmentDoc}
  ${RestaurantFieldsFragmentDoc}
`;
export const SendOneTimePasswordDocument = gql`
  mutation SendOneTimePassword($code: String!, $number: String!) {
    sendOneTimePassword(code: $code, number: $number) {
      status
      errors
    }
  }
`;
export type SendOneTimePasswordMutationFn = Apollo.MutationFunction<
  SendOneTimePasswordMutation,
  SendOneTimePasswordMutationVariables
>;

/**
 * __useSendOneTimePasswordMutation__
 *
 * To run a mutation, you first call `useSendOneTimePasswordMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSendOneTimePasswordMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [sendOneTimePasswordMutation, { data, loading, error }] = useSendOneTimePasswordMutation({
 *   variables: {
 *      code: // value for 'code'
 *      number: // value for 'number'
 *   },
 * });
 */
export function useSendOneTimePasswordMutation(
  baseOptions?: Apollo.MutationHookOptions<SendOneTimePasswordMutation, SendOneTimePasswordMutationVariables>
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useMutation<SendOneTimePasswordMutation, SendOneTimePasswordMutationVariables>(
    SendOneTimePasswordDocument,
    options
  );
}
export type SendOneTimePasswordMutationHookResult = ReturnType<typeof useSendOneTimePasswordMutation>;
export type SendOneTimePasswordMutationResult = Apollo.MutationResult<SendOneTimePasswordMutation>;
export type SendOneTimePasswordMutationOptions = Apollo.BaseMutationOptions<
  SendOneTimePasswordMutation,
  SendOneTimePasswordMutationVariables
>;
export const VerifyOneTimePasswordDocument = gql`
  mutation VerifyOneTimePassword($oneTimePassword: String!, $code: String!, $number: String!) {
    verifyOneTimePassword(oneTimePassword: $oneTimePassword, code: $code, number: $number) {
      user {
        ...UserFields
      }
      status
      token
      errors {
        oneTimePassword
      }
    }
  }
  ${UserFieldsFragmentDoc}
`;
export type VerifyOneTimePasswordMutationFn = Apollo.MutationFunction<
  VerifyOneTimePasswordMutation,
  VerifyOneTimePasswordMutationVariables
>;

/**
 * __useVerifyOneTimePasswordMutation__
 *
 * To run a mutation, you first call `useVerifyOneTimePasswordMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useVerifyOneTimePasswordMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [verifyOneTimePasswordMutation, { data, loading, error }] = useVerifyOneTimePasswordMutation({
 *   variables: {
 *      oneTimePassword: // value for 'oneTimePassword'
 *      code: // value for 'code'
 *      number: // value for 'number'
 *   },
 * });
 */
export function useVerifyOneTimePasswordMutation(
  baseOptions?: Apollo.MutationHookOptions<VerifyOneTimePasswordMutation, VerifyOneTimePasswordMutationVariables>
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useMutation<VerifyOneTimePasswordMutation, VerifyOneTimePasswordMutationVariables>(
    VerifyOneTimePasswordDocument,
    options
  );
}
export type VerifyOneTimePasswordMutationHookResult = ReturnType<typeof useVerifyOneTimePasswordMutation>;
export type VerifyOneTimePasswordMutationResult = Apollo.MutationResult<VerifyOneTimePasswordMutation>;
export type VerifyOneTimePasswordMutationOptions = Apollo.BaseMutationOptions<
  VerifyOneTimePasswordMutation,
  VerifyOneTimePasswordMutationVariables
>;
export const AddRestaurantAttachmentDocument = gql`
  mutation AddRestaurantAttachment($restaurantId: ID!, $attachment: Upload!) {
    addRestaurantAttachment(restaurantId: $restaurantId, attachment: $attachment) {
      restaurant {
        ...RestaurantFields
      }
      status
      errors
    }
  }
  ${RestaurantFieldsFragmentDoc}
`;
export type AddRestaurantAttachmentMutationFn = Apollo.MutationFunction<
  AddRestaurantAttachmentMutation,
  AddRestaurantAttachmentMutationVariables
>;

/**
 * __useAddRestaurantAttachmentMutation__
 *
 * To run a mutation, you first call `useAddRestaurantAttachmentMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useAddRestaurantAttachmentMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [addRestaurantAttachmentMutation, { data, loading, error }] = useAddRestaurantAttachmentMutation({
 *   variables: {
 *      restaurantId: // value for 'restaurantId'
 *      attachment: // value for 'attachment'
 *   },
 * });
 */
export function useAddRestaurantAttachmentMutation(
  baseOptions?: Apollo.MutationHookOptions<AddRestaurantAttachmentMutation, AddRestaurantAttachmentMutationVariables>
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useMutation<AddRestaurantAttachmentMutation, AddRestaurantAttachmentMutationVariables>(
    AddRestaurantAttachmentDocument,
    options
  );
}
export type AddRestaurantAttachmentMutationHookResult = ReturnType<typeof useAddRestaurantAttachmentMutation>;
export type AddRestaurantAttachmentMutationResult = Apollo.MutationResult<AddRestaurantAttachmentMutation>;
export type AddRestaurantAttachmentMutationOptions = Apollo.BaseMutationOptions<
  AddRestaurantAttachmentMutation,
  AddRestaurantAttachmentMutationVariables
>;
export const CreateRestaurantDocument = gql`
  mutation CreateRestaurant($name: String!) {
    createRestaurant(name: $name) {
      restaurant {
        ...RestaurantFields
      }
      network {
        ...NetworkFields
      }
      status
      errors
    }
  }
  ${RestaurantFieldsFragmentDoc}
  ${NetworkFieldsFragmentDoc}
`;
export type CreateRestaurantMutationFn = Apollo.MutationFunction<
  CreateRestaurantMutation,
  CreateRestaurantMutationVariables
>;

/**
 * __useCreateRestaurantMutation__
 *
 * To run a mutation, you first call `useCreateRestaurantMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateRestaurantMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createRestaurantMutation, { data, loading, error }] = useCreateRestaurantMutation({
 *   variables: {
 *      name: // value for 'name'
 *   },
 * });
 */
export function useCreateRestaurantMutation(
  baseOptions?: Apollo.MutationHookOptions<CreateRestaurantMutation, CreateRestaurantMutationVariables>
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useMutation<CreateRestaurantMutation, CreateRestaurantMutationVariables>(
    CreateRestaurantDocument,
    options
  );
}
export type CreateRestaurantMutationHookResult = ReturnType<typeof useCreateRestaurantMutation>;
export type CreateRestaurantMutationResult = Apollo.MutationResult<CreateRestaurantMutation>;
export type CreateRestaurantMutationOptions = Apollo.BaseMutationOptions<
  CreateRestaurantMutation,
  CreateRestaurantMutationVariables
>;
export const RemoveRestaurantAttachmentDocument = gql`
  mutation RemoveRestaurantAttachment($restaurantId: ID!, $attachmentId: ID!) {
    removeRestaurantAttachment(restaurantId: $restaurantId, attachmentId: $attachmentId) {
      restaurant {
        ...RestaurantFields
      }
      status
      errors
    }
  }
  ${RestaurantFieldsFragmentDoc}
`;
export type RemoveRestaurantAttachmentMutationFn = Apollo.MutationFunction<
  RemoveRestaurantAttachmentMutation,
  RemoveRestaurantAttachmentMutationVariables
>;

/**
 * __useRemoveRestaurantAttachmentMutation__
 *
 * To run a mutation, you first call `useRemoveRestaurantAttachmentMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useRemoveRestaurantAttachmentMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [removeRestaurantAttachmentMutation, { data, loading, error }] = useRemoveRestaurantAttachmentMutation({
 *   variables: {
 *      restaurantId: // value for 'restaurantId'
 *      attachmentId: // value for 'attachmentId'
 *   },
 * });
 */
export function useRemoveRestaurantAttachmentMutation(
  baseOptions?: Apollo.MutationHookOptions<
    RemoveRestaurantAttachmentMutation,
    RemoveRestaurantAttachmentMutationVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useMutation<RemoveRestaurantAttachmentMutation, RemoveRestaurantAttachmentMutationVariables>(
    RemoveRestaurantAttachmentDocument,
    options
  );
}
export type RemoveRestaurantAttachmentMutationHookResult = ReturnType<typeof useRemoveRestaurantAttachmentMutation>;
export type RemoveRestaurantAttachmentMutationResult = Apollo.MutationResult<RemoveRestaurantAttachmentMutation>;
export type RemoveRestaurantAttachmentMutationOptions = Apollo.BaseMutationOptions<
  RemoveRestaurantAttachmentMutation,
  RemoveRestaurantAttachmentMutationVariables
>;
export const UpdateCurrentUserInfoDocument = gql`
  mutation UpdateCurrentUserInfo($firstName: String!, $lastName: String) {
    updateCurrentUserInfo(firstName: $firstName, lastName: $lastName) {
      user {
        ...UserFields
      }
      status
      errors
    }
  }
  ${UserFieldsFragmentDoc}
`;
export type UpdateCurrentUserInfoMutationFn = Apollo.MutationFunction<
  UpdateCurrentUserInfoMutation,
  UpdateCurrentUserInfoMutationVariables
>;

/**
 * __useUpdateCurrentUserInfoMutation__
 *
 * To run a mutation, you first call `useUpdateCurrentUserInfoMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateCurrentUserInfoMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateCurrentUserInfoMutation, { data, loading, error }] = useUpdateCurrentUserInfoMutation({
 *   variables: {
 *      firstName: // value for 'firstName'
 *      lastName: // value for 'lastName'
 *   },
 * });
 */
export function useUpdateCurrentUserInfoMutation(
  baseOptions?: Apollo.MutationHookOptions<UpdateCurrentUserInfoMutation, UpdateCurrentUserInfoMutationVariables>
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useMutation<UpdateCurrentUserInfoMutation, UpdateCurrentUserInfoMutationVariables>(
    UpdateCurrentUserInfoDocument,
    options
  );
}
export type UpdateCurrentUserInfoMutationHookResult = ReturnType<typeof useUpdateCurrentUserInfoMutation>;
export type UpdateCurrentUserInfoMutationResult = Apollo.MutationResult<UpdateCurrentUserInfoMutation>;
export type UpdateCurrentUserInfoMutationOptions = Apollo.BaseMutationOptions<
  UpdateCurrentUserInfoMutation,
  UpdateCurrentUserInfoMutationVariables
>;
export const GetUserDocument = gql`
  query GetUser($userId: ID!) {
    user(userId: $userId) {
      ...UserFields
    }
  }
  ${UserFieldsFragmentDoc}
`;

/**
 * __useGetUserQuery__
 *
 * To run a query within a React component, call `useGetUserQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetUserQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetUserQuery({
 *   variables: {
 *      userId: // value for 'userId'
 *   },
 * });
 */
export function useGetUserQuery(baseOptions: Apollo.QueryHookOptions<GetUserQuery, GetUserQueryVariables>) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<GetUserQuery, GetUserQueryVariables>(GetUserDocument, options);
}
export function useGetUserLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<GetUserQuery, GetUserQueryVariables>) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<GetUserQuery, GetUserQueryVariables>(GetUserDocument, options);
}
export type GetUserQueryHookResult = ReturnType<typeof useGetUserQuery>;
export type GetUserLazyQueryHookResult = ReturnType<typeof useGetUserLazyQuery>;
export type GetUserQueryResult = Apollo.QueryResult<GetUserQuery, GetUserQueryVariables>;
